version: '3.8'
services:

  node_container:
    build: .
    image: prepared_node_js:1.1
    ports:
      - 9999:9999
    container_name: simulator_thesis

  postgresql_container:
    image: postgres:latest
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432:5432
    container_name: postgresql_thesis

  mysql_container:
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    ports:
      - 3306:3306
    container_name: mysql_thesis

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: postgresql_thesis # For PostgreSQL database
      #      ADMINER_DEFAULT_SERVER: mysql_thesis     # For MySQL database
      ADMINER_DESIGN: galkaev
    ports:
      - 8081:8080
    container_name: adminer_thesis